const mongoose = require('mongoose');
const item = require("./items");
const F_11 = new mongoose.Schema(
    {
        basicorder:{
            compliance:{
                label:{
                    type:String
                },
                openclose:item,
                prepofwork:item,
                finishing:item,
            },
            minimization:{
                label:{
                    type:String
                },
                floatingpeople:item,
                visitors:item,
                smokingarea:item
            },
            appearance:{
                label:{
                    type:String
                },
                clothappearance:item,
                shoesgloves:item
            },
            workerbehavior:{
                label:{
                    type:String
                },
                concentration:item,
                absenteeism:item
            }
        },
        cleanupsteps:{
            sortout:{
                label:{
                    type:String
                },
                parts:item,
                tools:item
            },
            setinorder:{
                label:{
                    type:String
                },
                materials:item,
                tools:item,
                cleaningtools:item,
            },
            shine:{
                label:{
                    type:String
                },
                equipment:item,
                process:item,
                interiorexterior:item
            },
            rightposition:{
                label:{
                    type:String
                },
                rawmaterials:item,
                tools:item,
            },
            rightcontainer:{
                label:{
                    type:String
                },
                standardized_rate:item
            },
            right_quantity:{
                label:{
                    type:String
                },
                material_depot:item,
                line_side:item
            },
            status_board:{
                label:{
                    type:String
                },
                production:item,
                quality:item
            },
            stack_height:item,
            warning_lights:item
        },
        manufacturing:{
            products_handling:item,
            work_standards:item,
            torque_managment:item,
            multi_skilling:item
        },
        equipment_maintenance:{
            issue_improvement:{
                label:{
                    type:String
                },
                identification:item,
                observation:item,
                contamination_source:item
            },
            my_machine:{
                label:{
                    type:String
                },
                cleaning:item,
                ownership:item,
            },
            improvement:{
                label:{
                    type:String
                },
                macine_performance:item,
                machine_visual:item,
                cleaning_tools:item
            }
        },
        smt:{
            temprature_control:item,
            msl_control:item,
            reel_materials_control:item,
            sub_materials_control:item,
            stencil_control:item,
            screen_printer_control:item,
            reflow_control:item,
            magazine_control:item,
            electric_iron_control:item
        },
        injection:{
            raw_material_control:item,
            drying_supply_control:item,
            mold_storage_control:item,
            cleaning_control:item,
            equipment_control:item,
            saftey_control:item,
        },
        press:{
            raw_material_control:item,
            mold_storage_control:item,
            cleaning_control:item,
            equipment_control:item,
            saftey_control:item,
        },
        warehouse:{
            materail:{
                label:{
                    type:String
                },
                managment:item,
                defective_stock:item,
                location:item,
                fifo:item
            },
            materail_depot:{
                label:{
                    type:String
                },
                managment:item,
                location:item,
                fifo:item,
            },
            product_warehouse_managment:{
                label:{
                    type:String
                },
                in_out:item,
                product_keeping:item,
                defective_stock:item,
                location:item,
                fifo:item,
            }
        },
        tools:{
            self_check:item,
            time_check:item,
            major_process:item,
            return_defects:item,
            quality_review:item,
            line_audit:item
        },
        esd:{
            grounding:item,
            transportaion:item,
            entrance:item,
            wrist_strap:item,
            pcba_handling:item,
        }
    }
)

module.exports = F_11;

